### ISSUE TITLE
 validator base class

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/ht_sip_validator#1]
- Constructor parameters - should take a SubmissionPackage
- needs a standard function name (e.g. valid?) to actually do the work
- determine standard way of returning errors and warnings from validator.
  - Validators return a default human-readable message
  - Assumption to start: Error messages are an (array of) hashes with agreed-on keys

**Comment by aelkiss** [comment]
Probably best to define the constructor parameters and entry point, then see what kind of error information we want to return and how best to do that.

**Comment by aelkiss** [comment]
There is an existing "BaseValidation" class, but the interface could use some thought.

**Comment by aelkiss** [comment]
See #24 - makes some changes to the base validator class to make it actually useful. Interface to getting errors is perhaps a bit of a code smell - probably better just to return errors from a public `validate` method rather than having public `valid?` call private `validate` method and then having the `errors` and `warnings` accessors throw errors if `valid?` hasn't yet been called. Will refactor tomorrow.

**Comment by malakai97** [comment]
* It sounds like we'll want to make validation output its own class.
* Unless you have duplicate keys, an array of hashes is just a hash.
* It is not essential for Validators to return human-readable messages, because that's a frontend issue.  However, that may be the best place to put the human-readable string for now, but we probably still want a machine-readable message on a separate key/method.

Assuming validators are stateless:

```ruby
module HathiTrust
  module Validation

    # A basic validation
    class Base

      # @param [SIP::SubmissionPackage] sip The sip to validate
      # @return [Validation::SomeSortOfValidationOutputClass]
      def validate(sip)
        # do stuff
        SomeSortOfValidationOutputClass.new(:base, other, stuff)
      end
    end
    
  end
end
```

I'm coming at this with the assumption that each specific validator will emit one _or more_ messages for an invalid SIP, e.g. a checksum validator might find several files that don't have the correct checksums.  Each of those messages will need a machine readable format and (possibly) also a human readable format.  Having a custom output class, even if it is very hash-like, insulates different parts of the code from that.

Sorry my thoughts are kind of all over the place.

**Comment by grosscol** [comment]
I like the validation output class.  We could implement `Validation::Message.is_error?` to make it simple to iterate through an array of them.

**Comment by aelkiss** [comment]
Agreed that validation output should be its own class.

I realized the way it is now (must first call valid?, then check errors) is basically the way ActiveRecord validations work. So at least it isn't _surprising_. I'm not sure that makes it _good_.

If we do want to have validators be stateless, It might still be helpful to define `valid?`, at least for testing, since then you don't need to

**Comment by aelkiss** [comment]
Base class exists and interface for returning messages is reasonably well defined as of https://github.com/hathitrust/ht_sip_validator/pull/32
