### ISSUE TITLE
Allow validators to be fatal & cause other validators not to even run

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/ht_sip_validator#5]
For example if meta.yml doesn't exist, don't bother checking anything about it because all the checks will fail with meaningless errors.

**Comment by aelkiss** [comment]
Implementation: each validator could have a set of other validators that it requires to have completed successfully before it runs. This should probably be set in the class for the validator, since it's not something you'd likely ever want or need to configure at run time (unlike perhaps validator error severity.)

We should avoid the temptation to abuse this functionality to set ordering dependencies for the purpose of sharing information between validators.

**Comment by malakai97** [comment]
I imagine very few people will want to do anything other than run all of the validators, so a graph may be overkill--we can probably get by with a default, linear ordering.

**Comment by grosscol** [comment]
I think the validator is the class to contain this logic.  A validator has visibility to the validations it is running and could know that if the first fails, don't bother with the others.  (maybe we should rename validator to validation_runner). 

I concur that I would like to avoid validations having to know or assume anything about that logic or their ordering. A test would be to run the validations in randomized order.  They would all have to handle the case of, "when the validation is given blank input", and the sip functions would have to pass the appropriate empty containers if something was missing.

In the case of #66, it would mean the image validation can assume that it will never see the case where there are no image files.  That is a piece of information that should have to be encoded somewhere, otherwise it's an assumption about the ordering of the validations.

**Comment by aelkiss** [comment]
We should discuss this issue in our meeting today since I'm not sure I entirely understand what you're proposing.

**Comment by aelkiss** [comment]
We should make it so that any individual validator
  - Should never cause a RuntimeError even if run out of order
  - Configuration file should specify ordering & dependencies.
