### ISSUE TITLE
refactor sip methods so they don't return nil

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/ht_sip_validator#71]
so that validators don't throw RuntimeErrors

**Comment by aelkiss** [comment]
Addressed by work on https://github.com/hathitrust/ht_sip_validator/tree/feature/issue_71

However this can still be problematic since YAML.load can return some unsavoury things when given the following input:

```ruby
YAML.load('') == false
```

```yaml
--- 
...
``` 
when loaded yields `nil`

Not sure where we should be checking for this... in `SIP#meta_yml` seems like the easiest place, but then maybe the method is misnamed and it should be something like `SIP#metadata` rather than implying it will always return verbatim what's in `meta.yml`..

**Comment by grosscol** [comment]
I concur that metadata is a better name, since it's not returning yml.  

That is rather unexpected behavior.  I would think both of those examples should be equivalent yaml, and should return the same thing.  I would have expected an empty hash in both those cases, but that is an erroneous association with yaml documents being hashes.
